In [1]:
library('tidyverse')

── Attaching packages ─────────────────────────────────────── tidyverse 1.2.1 ──

✔ ggplot2 3.2.0     ✔ purrr   0.3.2
✔ tibble  2.1.3     ✔ dplyr   0.8.3
✔ tidyr   0.8.3     ✔ stringr 1.4.0
✔ readr   1.3.1     ✔ forcats 0.4.0

── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()

In [2]:
df.marathon = read.csv('../data/marathon.csv')
df.marathon %>% head

  year name                       country       time       race.time MF
1 2019 Lawrence Cherono           Kenya         2H 7M 57S  2.132500  Men's
2 2018 Yuki Kawauchi              Japan         2H 15M 58S 2.266111  Men's
3 2017 Geoffrey Kirui             Kenya         2H 9M 37S  2.160278  Men's
4 2016 Lemi Berhanu               Ethiopia      2H 12M 45S 2.212500  Men's
5 2015 Lelisa Desisa              Ethiopia      2H 9M 17S  2.154722  Men's
6 2014 Mebrahtom "Meb" Keflezighi United States 2H 8M 37S  2.143611  Men's
  country.simple
1 Kenya
2 Japan
3 Kenya
4 Ethiopia
5 Ethiopia
6 United States

# Filter

- the filter operation does exactly what you expect given its name.

In [3]:
# e.g.

# iris %>% filter(Species == 'setosa', Petal.Width > 0.2)

- The syntax for the `equals` operator in R is `==`.
- Greater than (`>` or `>=`) and less than (`<` or `<=`) are intuitive.
- You can fitler on multiple columns by adding arguments to the filter operation.

Filter the marathon data to just the runners from Kenya.

In [3]:
df.marathon %>% filter(country=='Kenya')

   year name                      country time       race.time MF
1  2019 Lawrence Cherono          Kenya   2H 7M 57S  2.132500  Men's
2  2017 Geoffrey Kirui            Kenya   2H 9M 37S  2.160278  Men's
3  2012 Wesley Korir              Kenya   2H 12M 40S 2.211111  Men's
4  2011 Geoffrey Mutai            Kenya   2H 3M 2S   2.050556  Men's
5  2010 Robert Kiprono Cheruiyot  Kenya   2H 5M 52S  2.097778  Men's
6  2008 Robert Kipkoech Cheruiyot Kenya   2H 7M 46S  2.129444  Men's
7  2007 Robert Kipkoech Cheruiyot Kenya   2H 14M 13S 2.236944  Men's
8  2006 Robert Kipkoech Cheruiyot Kenya   2H 7M 14S  2.120556  Men's
9  2004 Timothy Cherigat          Kenya   2H 10M 37S 2.176944  Men's
10 2003 Robert Kipkoech Cheruiyot Kenya   2H 10M 11S 2.169722  Men's
11 2002 Rodgers Rop               Kenya   2H 9M 2S   2.150556  Men's
12 2000 Elijah Lagat              Kenya   2H 9M 47S  2.163056  Men's
13 1999 Joseph Chebet             Kenya   2H 9M 52S  2.164444  Men's
14 1998 Moses Tanui               Kenya   2H 7M 34S  2.126111  Men's
15 1997 Lameck Aguta              Kenya   2H 10M 34S 2.176111  Men's
16 1996 Moses Tanui               Kenya   2H 9M 15S  2.154167  Men's
17 1995 Cosmas Ndeti              Kenya   2H 9M 22S  2.156111  Men's
18 1994 Cosmas Ndeti              Kenya   2H 7M 15S  2.120833  Men's
19 1993 Cosmas Ndeti              Kenya   2H 9M 33S  2.159167  Men's
20 1992 Ibrahim Hussein           Kenya   2H 8M 14S  2.137222  Men's
21 1991 Ibrahim Hussein           Kenya   2H 11M 6S  2.185000  Men's
22 1988 Ibrahim Hussein           Kenya   2H 8M 43S  2.145278  Men's
23 2017 Edna Kiplagat             Kenya   2H 21M 52S 2.364444  Women's
24 2015 Caroline Rotich           Kenya   2H 24M 55S 2.415278  Women's
25 2013 Rita Jeptoo               Kenya   2H 26M 25S 2.440278  Women's
26 2012 Sharon Cherop             Kenya   2H 31M 50S 2.530556  Women's
27 2011 Caroline Kilel            Kenya   2H 22M 36S 2.376667  Women's
28 2009 Salina Kosgei             Kenya   2H 32M 16S 2.537778  Women's
29 2006 Rita Jeptoo               Kenya   2H 23M 38S 2.393889  Women's
30 2005 Catherine Ndereba         Kenya   2H 25M 13S 2.420278  Women's
31 2004 Catherine Ndereba         Kenya   2H 24M 27S 2.407500  Women's
32 2002 Margaret Okayo            Kenya   2H 20M 43S 2.345278  Women's
33 2001 Catherine Ndereba         Kenya   2H 23M 53S 2.398056  Women's
34 2000 Catherine Ndereba         Kenya   2H 26M 11S 2.436389  Women's
   country.simple
1  Kenya
2  Kenya
3  Kenya
4  Kenya
5  Kenya
6  Kenya
7  Kenya
8  Kenya
9  Kenya
10 Kenya
11 Kenya
12 Kenya
13 Kenya
14 Kenya
15 Kenya
16 Kenya
17 Kenya
18 Kenya
19 Kenya
20 Kenya
21 Kenya
22 Kenya
23 Kenya
24 Kenya
25 Kenya
26 Kenya
27 Kenya
28 Kenya
29 Kenya
30 Kenya
31 Kenya
32 Kenya
33 Kenya
34 Kenya

# Select

- select let's you include/exclude columns.

In [4]:
# e.g.

# iris %>% select(Species, Sepal.Length) %>% head

Select just the columns that represent runner names and country from the marathon data.

In [4]:
df.marathon %>% select(name , country)

    name                       country
1   Lawrence Cherono           Kenya
2   Yuki Kawauchi              Japan
3   Geoffrey Kirui             Kenya
4   Lemi Berhanu               Ethiopia
5   Lelisa Desisa              Ethiopia
6   Mebrahtom "Meb" Keflezighi United States
7   Lelisa Desisa              Ethiopia
8   Wesley Korir               Kenya
9   Geoffrey Mutai             Kenya
10  Robert Kiprono Cheruiyot   Kenya
11  Deriba Merga               Ethiopia
12  Robert Kipkoech Cheruiyot  Kenya
13  Robert Kipkoech Cheruiyot  Kenya
14  Robert Kipkoech Cheruiyot  Kenya
15  Hailu Negussie             Ethiopia
16  Timothy Cherigat           Kenya
17  Robert Kipkoech Cheruiyot  Kenya
18  Rodgers Rop                Kenya
19  Lee Bong-Ju                South Korea
20  Elijah Lagat               Kenya
21  Joseph Chebet              Kenya
22  Moses Tanui                Kenya
23  Lameck Aguta               Kenya
24  Moses Tanui                Kenya
25  Cosmas Ndeti               Kenya
26  Cosmas Ndeti               Kenya
27  Cosmas Ndeti               Kenya
28  Ibrahim Hussein            Kenya
29  Ibrahim Hussein            Kenya
30  Gelindo Bordin             Italy
⋮   ⋮                          ⋮
142 Catherine Ndereba          Kenya
143 Catherine Ndereba          Kenya
144 Fatuma Roba                Ethiopia
145 Fatuma Roba                Ethiopia
146 Fatuma Roba                Ethiopia
147 Uta Pippig                 Germany
148 Uta Pippig                 Germany
149 Uta Pippig                 Germany
150 Olga Markova               Russia
151 Olga Markova               Comm. Ind. States
152 Wanda Panfil               Poland
153 Rosa Mota                  Portugal
154 Ingrid Kristiansen         Norway
155 Rosa Mota                  Portugal
156 Rosa Mota                  Portugal
157 Ingrid Kristiansen         Norway
158 Lisa Larsen-Weidenbach     United States
159 Lorraine Moller            New Zealand
160 Joan Benoit                United States
161 Charlotte Teske            Germany
162 Allison Roe                New Zealand
163 Jacqueline Gareau          Canada
164 Joan Benoit                United States
165 Gayle S. Barron            United States
166 Michiko (Miki) Gorman      United States
167 Kim Merritt                United States
168 Liane Winter               Germany
169 Michiko (Miki) Gorman      United States
170 Jacqueline A. Hansen       United States
171 Nina Kuscsik               United States

# Putting it all together

Use `group_by`, `filter`, and `summarize` to show the best race times for US and Kenyan women runners. (*Hint: use the `%in%` operator to filter by two values for one column*). Fill in the missing pieces below:

In [5]:
 df.marathon %>%
     filter(MF == "Women's", country %in% c('United States', 'Kenya')) %>%
     group_by(country) %>%
     summarize(best.race.time = min(race.time))

  country       best.race.time
1 Kenya         2.345278
2 United States 2.378611

Use `filter`, `select`, `head`, and `arrange` to show the best women's race times in the data and the country of the runners. Fill in the missing pieces below:

In [8]:
df.marathon %>%
    filter(MF == "Women's") %>%
    select(country, race.time) %>%
    arrange(race.time) %>%
    head(10)
#head above would give 10 best race times

   country       race.time
1  Ethiopia      2.333056
2  Kenya         2.345278
3  Germany       2.362500
4  Kenya         2.364444
5  Kenya         2.376667
6  United States 2.378611
7  Ethiopia      2.389167
8  Ethiopia      2.390278
9  Ethiopia      2.391944
10 Kenya         2.393889

In [9]:
df.marathon %>%
    filter(MF == "Women's") %>%
    select(country, race.time) %>%
    arrange(desc(race.time)) %>%
    head(10)
#desc is descending order of racetimes

   country       race.time
1  United States 3.173889
2  United States 3.099722
3  United States 2.809167
4  United States 2.786389
5  United States 2.786111
6  United States 2.747778
7  Germany       2.706667
8  United States 2.665000
9  United States 2.587500
10 Canada        2.574444

What's the best race time ever for a US man?

In [10]:
df.marathon %>% 
    filter(MF=="Men's", country=="United States") %>%
    arrange(race.time) %>%
    head(1)

  year name                       country       time      race.time MF
1 2014 Mebrahtom "Meb" Keflezighi United States 2H 8M 37S 2.143611  Men's
  country.simple
1 United States

In [12]:
df.marathon %>% 
    filter(MF=="Men's", country=="United States") %>%
    top_n(1,-race.time)
#top_n orders in descending order by default

  year name                       country       time      race.time MF
1 2014 Mebrahtom "Meb" Keflezighi United States 2H 8M 37S 2.143611  Men's
  country.simple
1 United States

How does the best US men's time compare the the best race time in the data overall?

In [13]:
df.marathon %>%
    top_n(1,-race.time)

  year name           country time     race.time MF    country.simple
1 2011 Geoffrey Mutai Kenya   2H 3M 2S 2.050556  Men's Kenya

# Bonus

For all countries with at least 5 winners in the men's category, which country has the best median race time in the men's category? (*Hint: use the `n()` function to count the winners by country.)

In [14]:
# This should get you started. It adds a column "N.winners" that represents the
# total winners from the runner's country.

df.marathon %>%
    filter(MF == "Men's") %>%
    group_by(country) %>%
    mutate(N.winners = n()) %>% head
    filter(N.winners >= 5) %>%

  year name                       country       time       race.time MF
1 2019 Lawrence Cherono           Kenya         2H 7M 57S  2.132500  Men's
2 2018 Yuki Kawauchi              Japan         2H 15M 58S 2.266111  Men's
3 2017 Geoffrey Kirui             Kenya         2H 9M 37S  2.160278  Men's
4 2016 Lemi Berhanu               Ethiopia      2H 12M 45S 2.212500  Men's
5 2015 Lelisa Desisa              Ethiopia      2H 9M 17S  2.154722  Men's
6 2014 Mebrahtom "Meb" Keflezighi United States 2H 8M 37S  2.143611  Men's
  country.simple N.winners
1 Kenya          22
2 Japan           9
3 Kenya          22
4 Ethiopia        6
5 Ethiopia        6
6 United States  44

In [20]:
tmp1 = df.marathon %>%
    filter(MF == "Men's") %>%
    group_by(country) %>%
    count() %>%
    filter (n>=5)
tmp1
countries.gt5 = tmp1$country
countries.gt5
df.marathon %>% 
    filter(country %in% countries.gt5)

  country       n
1 Canada        16
2 Ethiopia       6
3 Finland        7
4 Japan          9
5 Kenya         22
6 United States 44

[1] Canada        Ethiopia      Finland       Japan         Kenya
[6] United States
25 Levels: Australia Belgium Canada Colombia Comm. Ind. States ... Yugoslavia

    year name                       country       time       race.time MF
1   2019 Lawrence Cherono           Kenya         2H 7M 57S  2.132500  Men's
2   2018 Yuki Kawauchi              Japan         2H 15M 58S 2.266111  Men's
3   2017 Geoffrey Kirui             Kenya         2H 9M 37S  2.160278  Men's
4   2016 Lemi Berhanu               Ethiopia      2H 12M 45S 2.212500  Men's
5   2015 Lelisa Desisa              Ethiopia      2H 9M 17S  2.154722  Men's
6   2014 Mebrahtom "Meb" Keflezighi United States 2H 8M 37S  2.143611  Men's
7   2013 Lelisa Desisa              Ethiopia      2H 10M 22S 2.172778  Men's
8   2012 Wesley Korir               Kenya         2H 12M 40S 2.211111  Men's
9   2011 Geoffrey Mutai             Kenya         2H 3M 2S   2.050556  Men's
10  2010 Robert Kiprono Cheruiyot   Kenya         2H 5M 52S  2.097778  Men's
11  2009 Deriba Merga               Ethiopia      2H 8M 42S  2.145000  Men's
12  2008 Robert Kipkoech Cheruiyot  Kenya         2H 7M 46S  2.129444  Men's
13  2007 Robert Kipkoech Cheruiyot  Kenya         2H 14M 13S 2.236944  Men's
14  2006 Robert Kipkoech Cheruiyot  Kenya         2H 7M 14S  2.120556  Men's
15  2005 Hailu Negussie             Ethiopia      2H 11M 45S 2.195833  Men's
16  2004 Timothy Cherigat           Kenya         2H 10M 37S 2.176944  Men's
17  2003 Robert Kipkoech Cheruiyot  Kenya         2H 10M 11S 2.169722  Men's
18  2002 Rodgers Rop                Kenya         2H 9M 2S   2.150556  Men's
19  2000 Elijah Lagat               Kenya         2H 9M 47S  2.163056  Men's
20  1999 Joseph Chebet              Kenya         2H 9M 52S  2.164444  Men's
21  1998 Moses Tanui                Kenya         2H 7M 34S  2.126111  Men's
22  1997 Lameck Aguta               Kenya         2H 10M 34S 2.176111  Men's
23  1996 Moses Tanui                Kenya         2H 9M 15S  2.154167  Men's
24  1995 Cosmas Ndeti               Kenya         2H 9M 22S  2.156111  Men's
25  1994 Cosmas Ndeti               Kenya         2H 7M 15S  2.120833  Men's
26  1993 Cosmas Ndeti               Kenya         2H 9M 33S  2.159167  Men's
27  1992 Ibrahim Hussein            Kenya         2H 8M 14S  2.137222  Men's
28  1991 Ibrahim Hussein            Kenya         2H 11M 6S  2.185000  Men's
29  1989 Abebe Mekonnen             Ethiopia      2H 9M 6S   2.151667  Men's
30  1988 Ibrahim Hussein            Kenya         2H 8M 43S  2.145278  Men's
⋮   ⋮    ⋮                          ⋮             ⋮          ⋮         ⋮
106 2018 Desiree Linden             United States 2H 39M 54S 2.665000  Women's
107 2017 Edna Kiplagat              Kenya         2H 21M 52S 2.364444  Women's
108 2016 Atsede Baysa               Ethiopia      2H 29M 19S 2.488611  Women's
109 2015 Caroline Rotich            Kenya         2H 24M 55S 2.415278  Women's
110 2014 Buzunesh Deba              Ethiopia      2H 19M 59S 2.333056  Women's
111 2013 Rita Jeptoo                Kenya         2H 26M 25S 2.440278  Women's
112 2012 Sharon Cherop              Kenya         2H 31M 50S 2.530556  Women's
113 2011 Caroline Kilel             Kenya         2H 22M 36S 2.376667  Women's
114 2010 Teyba Erkesso              Ethiopia      2H 26M 11S 2.436389  Women's
115 2009 Salina Kosgei              Kenya         2H 32M 16S 2.537778  Women's
116 2008 Dire Tune                  Ethiopia      2H 25M 25S 2.423611  Women's
117 2006 Rita Jeptoo                Kenya         2H 23M 38S 2.393889  Women's
118 2005 Catherine Ndereba          Kenya         2H 25M 13S 2.420278  Women's
119 2004 Catherine Ndereba          Kenya         2H 24M 27S 2.407500  Women's
120 2002 Margaret Okayo             Kenya         2H 20M 43S 2.345278  Women's
121 2001 Catherine Ndereba          Kenya         2H 23M 53S 2.398056  Women's
122 2000 Catherine Ndereba          Kenya         2H 26M 11S 2.436389  Women's
123 1999 Fatuma Roba                Ethiopia      2H 23M 25S 2.390278  Women's
124 1998 Fatuma Roba                Ethiopia      2H 23M 21S 2.389167  Women's
125 1997 Fatuma Roba                Ethiopia      2H 26M 23S 2.439722  Women's
126 1985 Lisa Larsen-Weidenbach     United States 2H 34M 6S  2.568333  Women's
127 1983 Joan Benoit                United States 2H 22M 43S 2.378611  Women's
128 1980 Jacqueline Gareau          Canada        2H 34M 28S 2.574444  Women's
129 1979 Joan Benoit                United States 2H 35M 15S 2.587500  Women's
130 1978 Gayle S. Barron            United States 2H 44M 52S 2.747778  Women's
131 1977 Michiko (Miki) Gorman      United States 2H 48M 33S 2.809167  Women's
132 1976 Kim Merritt                United States 2H 47M 10S 2.786111  Women's
133 1974 Michiko (Miki) Gorman      United States 2H 47M 11S 2.786389  Women's
134 1973 Jacqueline A. Hansen       United States 3H 5M 59S  3.099722  Women's
135 1972 Nina Kuscsik               United States 3H 10M 26S 3.173889  Women's
    country.simple
1   Kenya
2   Japan
3   Kenya
4   Ethiopia
5   Ethiopia
6   United States
7   Ethiopia
8   Kenya
9   Kenya
10  Kenya
11  Ethiopia
12  Kenya
13  Kenya
14  Kenya
15  Ethiopia
16  Kenya
17  Kenya
18  Kenya
19  Kenya
20  Kenya
21  Kenya
22  Kenya
23  Kenya
24  Kenya
25  Kenya
26  Kenya
27  Kenya
28  Kenya
29  Ethiopia
30  Kenya
⋮   ⋮
106 United States
107 Kenya
108 Ethiopia
109 Kenya
110 Ethiopia
111 Kenya
112 Kenya
113 Kenya
114 Ethiopia
115 Kenya
116 Ethiopia
117 Kenya
118 Kenya
119 Kenya
120 Kenya
121 Kenya
122 Kenya
123 Ethiopia
124 Ethiopia
125 Ethiopia
126 United States
127 United States
128 other
129 United States
130 United States
131 United States
132 United States
133 United States
134 United States
135 United States